# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# Use a package of configuration called an orb, see https://circleci.com/docs/2.0/orb-intro/
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.3.1
  cypress: cypress-io/cypress@1.6.0

jobs:
  build-and-test:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: 'circleci/node:9.6.1'
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
  start-server-for-cypress:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: 'circleci/node:9.6.1'
    steps:
      - checkout
      - run: yarn install
      - run: yarn run CI

workflows:
  # Name the workflow "Welcome"
  Welcome:
    # Run the welcome/run job in its own container
    jobs:
      - build-and-test
      - cypress/install:
          build: 'yarn run build'  # run a custom app build step
      - cypress/run:
          requires:
            - cypress/install
          start: 'yarn start'